// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace ReportingSolution.Data.BlazorServerModels;

public partial class BlazorServerContext : DbContext
{
    public BlazorServerContext(DbContextOptions<BlazorServerContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Books>(entity =>
        {
            entity.Property(e => e.Id)
                .HasMaxLength(255)
                .HasColumnName("id");
            entity.Property(e => e.Author)
                .HasMaxLength(255)
                .HasColumnName("author");
            entity.Property(e => e.Genre)
                .HasMaxLength(255)
                .HasColumnName("genre");
            entity.Property(e => e.Price).HasColumnName("price");
            entity.Property(e => e.PubDate)
                .HasColumnType("datetime")
                .HasColumnName("pub_date");
            entity.Property(e => e.Review)
                .HasMaxLength(255)
                .HasColumnName("review");
            entity.Property(e => e.Title)
                .HasMaxLength(255)
                .HasColumnName("title");
        });

        modelBuilder.Entity<Developers>(entity =>
        {
            entity.Property(e => e.Experience).HasColumnType("decimal(18, 2)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}