// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReportingSolution.Data.BlazorServerModels;

public partial class Books
{
    public string Id { get; set; }

    public string Author { get; set; }

    public string Title { get; set; }

    public string Genre { get; set; }

    public float? Price { get; set; }

    public DateTime? PubDate { get; set; }

    public string Review { get; set; }
}