// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ReportingSolution.Data.NoSqlModel;

public partial class Users
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public byte[] LastModified { get; set; }
}